import{useEffect,useMemo,useState}from'react';import{CloudSun,CloudRain,Droplets,Globe2,MapPin,Moon,Search,Sun,Thermometer,Wind,RefreshCw,Navigation,Eye,CloudFog,CloudLightning,Menu,X}from'lucide-react';import{Area,AreaChart,ResponsiveContainer,Tooltip,XAxis}from'recharts';

type Place={name:string;country:string;admin1?:string;latitude:number;longitude:number;timezone:string};type Weather={current:any;hourly:any;daily:any;sunrise:string;sunset:string};
const DEFAULT:Place={name:'Lucknow',country:'India',latitude:26.8467,longitude:80.9462,timezone:'Asia/Kolkata'};
const label=(code:number)=>code===0?'Clear sky':code<=3?'Partly cloudy':code<=48?'Hazy / foggy':code<=57?'Drizzle':code<=67?'Rain':code<=77?'Snow':code<=82?'Rain showers':code<=86?'Snow showers':'Thunderstorm';
const icon=(code:number,size=34)=>code===0?<Sun size={size}/>:code<=3?<CloudSun size={size}/>:code<=48?<CloudFog size={size}/>:code>=95?<CloudLightning size={size}/>:<CloudRain size={size}/>;
const load=async(p:Place):Promise<Weather>=>{const u='https://api.open-meteo.com/v1/forecast?latitude='+p.latitude+'&longitude='+p.longitude+'&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,surface_pressure,wind_speed_10m,wind_direction_10m,visibility&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset&forecast_days=7&timezone=auto';const r=await fetch(u);if(!r.ok)throw Error('Weather request failed');return r.json()};
const searchPlaces=async(q:string)=>{const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=6&language=en&format=json');if(!r.ok)return[];const j=await r.json();return(j.results||[]).map((x:any)=>({name:x.name,country:x.country||'',admin1:x.admin1,latitude:x.latitude,longitude:x.longitude,timezone:x.timezone||'auto'}))};

export default function App(){const[p,setP]=useState(DEFAULT),[w,setW]=useState<Weather|null>(null),[query,setQuery]=useState(''),[places,setPlaces]=useState<Place[]>([]),[dark,setDark]=useState(true),[busy,setBusy]=useState(true),[open,setOpen]=useState(false);
const refresh=()=>{setBusy(true);load(p).then(setW).catch(()=>setW(null)).finally(()=>setBusy(false))};useEffect(refresh,[p]);useEffect(()=>{const t=setTimeout(()=>{if(query.trim().length>1)searchPlaces(query).then(setPlaces)},300);return()=>clearTimeout(t)},[query]);
const hours=useMemo(()=>w?w.hourly.time.slice(0,24).map((t:string,i:number)=>({time:new Date(t).toLocaleTimeString([], {hour:'numeric'}),temp:Math.round(w.hourly.temperature_2m[i])})):[],[w]);const c=w?.current;const today=w?.daily;
return <div className={dark?'shell dark':'shell'}><div className={'sky weather-'+(c?.weather_code??0)}><div className="moon"/><div className="sun-glow"/></div>
<header><button className="icon mobile" onClick={()=>setOpen(true)}><Menu/></button><div className="logo"><div className="mark"><CloudSun/></div><div><b>Clima-Tact</b><span>Live weather observatory</span></div></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a city…"/>{places.length>0&&<div className="results">{places.map(x=><button key={x.latitude+x.longitude} onClick={()=>{setP(x);setQuery('');setPlaces([])}}><MapPin size={15}/><span><b>{x.name}</b><small>{x.admin1?x.admin1+', ':''}{x.country}</small></span></button>)}</div>}</div><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header>
<div className={open?'drawer show':'drawer'}><button className="icon close" onClick={()=>setOpen(false)}><X/></button><b>Clima-Tact</b><span>Atmosphere, made visible.</span></div>
<main><section className="intro"><div><p>LIVE ATMOSPHERE</p><h1>{p.name}</h1><div className="place"><MapPin size={15}/>{p.country}<span>•</span>{c?new Date(c.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Connecting'}</div></div><button className="refresh" onClick={refresh}><RefreshCw size={16} className={busy?'spin':''}/> Refresh</button></section>
<section className="hero-grid"><article className="glass hero"><div><span className="eyebrow">NOW</span><div className="temp">{busy?'--':Math.round(c?.temperature_2m)}<sup>°C</sup></div><h2>{busy?'Reading the atmosphere…':label(c?.weather_code)}</h2><p>Feels like {busy?'--':Math.round(c?.apparent_temperature)}° · Visibility {busy?'--':Math.round((c?.visibility||0)/1000)} km</p></div><div className="weather-icon">{icon(c?.weather_code,82)}</div><div className="hero-strip"><span><Droplets/> {c?.relative_humidity_2m??'--'}% <small>humidity</small></span><span><Wind/> {c?Math.round(c.wind_speed_10m):'--'} km/h <small>wind</small></span><span><Navigation style={{transform:'rotate('+(c?.wind_direction_10m||0)+'deg)'}}/> {c?Math.round(c.wind_direction_10m):'--'}° <small>direction</small></span></div></article>
<article className="glass side"><div className="side-head"><div><span className="eyebrow">TODAY</span><h3>Sky rhythm</h3></div><span className="badge">LIVE</span></div><div className="sunline"><div><Sun/><small>Sunrise</small><b>{today?.sunrise?.[0]?new Date(today.sunrise[0]).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'--'}</b></div><div className="arc"><i/></div><div><Sun/><small>Sunset</small><b>{today?.sunset?.[0]?new Date(today.sunset[0]).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'--'}</b></div></div><div className="side-metrics"><div><span>High</span><b>{today?Math.round(today.temperature_2m_max[0]):'--'}°</b></div><div><span>Low</span><b>{today?Math.round(today.temperature_2m_min[0]):'--'}°</b></div><div><span>Rain chance</span><b>{today?today.precipitation_probability_max[0]:'--'}%</b></div></div></article></section>
<section className="lower-grid"><article className="glass wide"><div className="card-head"><div><span className="eyebrow">NEXT 24 HOURS</span><h3>Temperature flow</h3></div><span className="peak"><Thermometer/> {w?Math.max(...hours.map(x=>x.temp)):'--'}° peak</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={hours}><defs><linearGradient id="tempFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".28"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="time" tickLine={false} axisLine={false} interval={2} tick={{fontSize:10}}/><Tooltip contentStyle={{background:'rgba(9,20,34,.92)',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,fontSize:12,color:'#fff'}}/><Area type="monotone" dataKey="temp" stroke="currentColor" fill="url(#tempFill)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></article>
<article className="glass week"><div className="card-head"><div><span className="eyebrow">7 DAY OUTLOOK</span><h3>Next on the horizon</h3></div></div>{w?.daily?.time.map((d:string,i:number)=><div className="day" key={d}><span>{i===0?'Today':new Date(d+'T12:00:00').toLocaleDateString([], {weekday:'short'})}</span><span className="mini-icon">{icon(w.daily.weather_code[i],22)}</span><small>{label(w.daily.weather_code[i])}</small><b>{Math.round(w.daily.temperature_2m_max[i])}°</b><em>{Math.round(w.daily.temperature_2m_min[i])}°</em></div>)}</article></section>
<section className="science"><span>CLIMA-TACT</span><strong>Weather is the moment. Climate is the memory.</strong><p>Explore live atmospheric conditions first, then trace longer-term patterns, anomalies, and environmental change.</p><div className="science-tags"><span><Globe2/> Weather layers</span><span><Eye/> Atmospheric visibility</span><span><CloudRain/> Precipitation</span></div></section></main></div>}